AllCops:
  NewCops: enable

Style/ClassAndModuleChildren:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Layout/LineLength:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Style/Documentation:
  Enabled: false

Lint/EmptyBlock:
  Enabled: false

Style/MultilineBlockChain:
  Enabled: false

Naming/VariableNumber:
  Exclude:
    - 'app/graphql/**/*'
    - 'app/services/plant_sample_upload.rb'

Metrics/AbcSize:
  Exclude:
    - 'db/migrate/*'
    - 'app/services/*.rb'

Metrics/ClassLength:
  Exclude:
    - 'app/graphql/types/query_type.rb'
    - 'app/services/tube_upload.rb'

Naming/MethodParameterName:
  Exclude:
    - 'app/services/tube_upload.rb'
    - 'app/controllers/graphql_controller.rb'

Naming/MethodName:
  Exclude:
    - 'app/graphql/**/*'

Metrics/ModuleLength:
  Exclude:
    - 'app/services/plant_sample_upload.rb'
