version: '2'
services:
  db:
    image: postgres:14.4
    restart: always
    environment:
        PSQL_ROOT_PASSWORD: password
        PSQL_DATABASE: noteapp
        PSQL_USER: appuser
        PSQL_PASSWORD: password
    ports:
        - "3307:3306"
    app:
        build: .
        command: bundle exec rails s -p 3000 -b '0.0.0.0'
        volumes:
            - ".:/noteapp"
        ports:
            - "3001:3000"
        depends_on:
          - db
        links:  
             - db