version: '3.9'

services:
  postgres:
    image: postgres:14.4
    environment:
      POSTGRES_USER: plant_ui
      POSTGRES_PASSWORD: "${PLANT_UI_DATABASE_PASSWORD}"
    ports:
      - '5432:5432'
    volumes:
      - plant-ui-postgres:/var/lib/postgresql/data
    env_file:
      - .env

  redis:
    image: redis:7.0
    ports:
      - '6379:6379'
    volumes:
      - plant-ui-redis:/var/lib/redis/data

  app:
    build:
      context: .
    volumes:
      - ./plant-ui:/opt/plant-ui
    links:
      - postgres
      - redis
    ports:
      - '3000:3000'
    env_file:
      - .env

  nginx:
    build:
      context: .
      dockerfile: ./Dockerfile.nginx
    links:
      - app
    ports:
      - '3010:3010'

volumes:
  plant-ui-postgres:
  plant-ui-redis: