#!/usr/bin/env ruby
# frozen_string_literal: true

require 'csv'

CSV.open('truncated_seed_tubes.csv', 'wb') do |csv|
  CSV.foreach((ARGV[0]).to_s).with_index do |row, line|
    csv << row if (line % 20).zero?
  end
end
