#!/usr/bin/env ruby
# frozen_string_literal: true

require 'csv'

CSV.open('truncated_seed_tubes.csv', 'wb') do |out|
  CSV.foreach((ARGV[0]).to_s, headers: true).with_index do |row, line|
    out << row if (line % 20).zero?
  end
end
